

server:
  port: 8090

spring:
  application:
    name: Product Management
  datasource:
    url: jdbc:h2:mem:product-management
    driver-class-name: org.h2.Driver
    username: root
    password:
  h2:
    console:
      enabled: true
      path: /h2-db
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
